version: '3.1'

services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - ~/docker:/var/lib/registry
      - ./auth:/auth
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /auth/registry_auth.crt
      REGISTRY_HTTP_TLS_KEY: /auth/registry_auth.key
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
